// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearLoginThrottle = `-- name: ClearLoginThrottle :exec
DELETE FROM login_throttle WHERE scope = $1 AND key = $2
`

type ClearLoginThrottleParams struct {
	Scope string
	Key   []byte
}

func (q *Queries) ClearLoginThrottle(ctx context.Context, arg ClearLoginThrottleParams) error {
	_, err := q.db.Exec(ctx, clearLoginThrottle, arg.Scope, arg.Key)
	return err
}

const consumeCode = `-- name: ConsumeCode :one
UPDATE one_time_codes SET consumed_at = $1
WHERE id = $2 AND consumed_at IS NULL
RETURNING user_id
`

type ConsumeCodeParams struct {
	Now pgtype.Timestamptz
	ID  pgtype.UUID
}

func (q *Queries) ConsumeCode(ctx context.Context, arg ConsumeCodeParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, consumeCode, arg.Now, arg.ID)
	var user_id pgtype.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const countCodeAttempt = `-- name: CountCodeAttempt :execrows
UPDATE one_time_codes SET attempts = attempts + 1
WHERE id = $1 AND consumed_at IS NULL AND attempts < $2::integer
`

type CountCodeAttemptParams struct {
	ID          pgtype.UUID
	MaxAttempts int32
}

func (q *Queries) CountCodeAttempt(ctx context.Context, arg CountCodeAttemptParams) (int64, error) {
	result, err := q.db.Exec(ctx, countCodeAttempt, arg.ID, arg.MaxAttempts)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUserCodes = `-- name: DeleteUserCodes :exec
DELETE FROM one_time_codes WHERE user_id = $1 AND purpose = $2
`

type DeleteUserCodesParams struct {
	UserID  pgtype.UUID
	Purpose string
}

func (q *Queries) DeleteUserCodes(ctx context.Context, arg DeleteUserCodesParams) error {
	_, err := q.db.Exec(ctx, deleteUserCodes, arg.UserID, arg.Purpose)
	return err
}

const insertCode = `-- name: InsertCode :exec
INSERT INTO one_time_codes (id, user_id, purpose, code_hash, expires_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertCodeParams struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Purpose   string
	CodeHash  []byte
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) InsertCode(ctx context.Context, arg InsertCodeParams) error {
	_, err := q.db.Exec(ctx, insertCode,
		arg.ID,
		arg.UserID,
		arg.Purpose,
		arg.CodeHash,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const insertSession = `-- name: InsertSession :exec
INSERT INTO sessions (id, family_id, user_id, access_hash, access_expires_at, refresh_hash, refresh_expires_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertSessionParams struct {
	ID               pgtype.UUID
	FamilyID         pgtype.UUID
	UserID           pgtype.UUID
	AccessHash       []byte
	AccessExpiresAt  pgtype.Timestamptz
	RefreshHash      []byte
	RefreshExpiresAt pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.Exec(ctx, insertSession,
		arg.ID,
		arg.FamilyID,
		arg.UserID,
		arg.AccessHash,
		arg.AccessExpiresAt,
		arg.RefreshHash,
		arg.RefreshExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const liveCode = `-- name: LiveCode :one
SELECT id, code_hash, expires_at, attempts FROM one_time_codes
WHERE user_id = $1 AND purpose = $2 AND consumed_at IS NULL
`

type LiveCodeParams struct {
	UserID  pgtype.UUID
	Purpose string
}

type LiveCodeRow struct {
	ID        pgtype.UUID
	CodeHash  []byte
	ExpiresAt pgtype.Timestamptz
	Attempts  int32
}

func (q *Queries) LiveCode(ctx context.Context, arg LiveCodeParams) (LiveCodeRow, error) {
	row := q.db.QueryRow(ctx, liveCode, arg.UserID, arg.Purpose)
	var i LiveCodeRow
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.Attempts,
	)
	return i, err
}

const loginThrottle = `-- name: LoginThrottle :one
SELECT failures, last_failure_at, next_allowed_at FROM login_throttle
WHERE scope = $1 AND key = $2
`

type LoginThrottleParams struct {
	Scope string
	Key   []byte
}

type LoginThrottleRow struct {
	Failures      int32
	LastFailureAt pgtype.Timestamptz
	NextAllowedAt pgtype.Timestamptz
}

func (q *Queries) LoginThrottle(ctx context.Context, arg LoginThrottleParams) (LoginThrottleRow, error) {
	row := q.db.QueryRow(ctx, loginThrottle, arg.Scope, arg.Key)
	var i LoginThrottleRow
	err := row.Scan(&i.Failures, &i.LastFailureAt, &i.NextAllowedAt)
	return i, err
}

const markEmailVerified = `-- name: MarkEmailVerified :exec
UPDATE users SET email_verified_at = $1, updated_at = $1, version = version + 1
WHERE id = $2 AND email_verified_at IS NULL
`

type MarkEmailVerifiedParams struct {
	Now pgtype.Timestamptz
	ID  pgtype.UUID
}

func (q *Queries) MarkEmailVerified(ctx context.Context, arg MarkEmailVerifiedParams) error {
	_, err := q.db.Exec(ctx, markEmailVerified, arg.Now, arg.ID)
	return err
}

const markSessionReplaced = `-- name: MarkSessionReplaced :exec
UPDATE sessions SET replaced_by = $1, revoked_at = $2
WHERE id = $3
`

type MarkSessionReplacedParams struct {
	ReplacedBy pgtype.UUID
	Now        pgtype.Timestamptz
	ID         pgtype.UUID
}

func (q *Queries) MarkSessionReplaced(ctx context.Context, arg MarkSessionReplacedParams) error {
	_, err := q.db.Exec(ctx, markSessionReplaced, arg.ReplacedBy, arg.Now, arg.ID)
	return err
}

const recordLoginFailure = `-- name: RecordLoginFailure :one
INSERT INTO login_throttle (scope, key, failures, last_failure_at, next_allowed_at)
VALUES ($1, $2, 1, $3, $3)
ON CONFLICT (scope, key) DO UPDATE
    SET failures = CASE WHEN login_throttle.last_failure_at <= $4 THEN 1
                        ELSE login_throttle.failures + 1 END,
        last_failure_at = excluded.last_failure_at
RETURNING failures
`

type RecordLoginFailureParams struct {
	Scope       string
	Key         []byte
	Now         pgtype.Timestamptz
	StaleBefore pgtype.Timestamptz
}

// Counts a failure; a count whose last failure is at or before @stale_before
// starts again at 1.
func (q *Queries) RecordLoginFailure(ctx context.Context, arg RecordLoginFailureParams) (int32, error) {
	row := q.db.QueryRow(ctx, recordLoginFailure,
		arg.Scope,
		arg.Key,
		arg.Now,
		arg.StaleBefore,
	)
	var failures int32
	err := row.Scan(&failures)
	return failures, err
}

const revokeSessionFamily = `-- name: RevokeSessionFamily :exec
UPDATE sessions SET revoked_at = $1
WHERE family_id = $2 AND revoked_at IS NULL
`

type RevokeSessionFamilyParams struct {
	Now      pgtype.Timestamptz
	FamilyID pgtype.UUID
}

func (q *Queries) RevokeSessionFamily(ctx context.Context, arg RevokeSessionFamilyParams) error {
	_, err := q.db.Exec(ctx, revokeSessionFamily, arg.Now, arg.FamilyID)
	return err
}

const revokeUserSessions = `-- name: RevokeUserSessions :exec
UPDATE sessions SET revoked_at = $1
WHERE user_id = $2 AND revoked_at IS NULL
`

type RevokeUserSessionsParams struct {
	Now    pgtype.Timestamptz
	UserID pgtype.UUID
}

func (q *Queries) RevokeUserSessions(ctx context.Context, arg RevokeUserSessionsParams) error {
	_, err := q.db.Exec(ctx, revokeUserSessions, arg.Now, arg.UserID)
	return err
}

const sessionByAccessHash = `-- name: SessionByAccessHash :one
SELECT s.id, s.family_id, s.user_id, s.access_expires_at, s.revoked_at, u.email_verified_at
FROM sessions s JOIN users u ON u.id = s.user_id
WHERE s.access_hash = $1
`

type SessionByAccessHashRow struct {
	ID              pgtype.UUID
	FamilyID        pgtype.UUID
	UserID          pgtype.UUID
	AccessExpiresAt pgtype.Timestamptz
	RevokedAt       pgtype.Timestamptz
	EmailVerifiedAt pgtype.Timestamptz
}

func (q *Queries) SessionByAccessHash(ctx context.Context, accessHash []byte) (SessionByAccessHashRow, error) {
	row := q.db.QueryRow(ctx, sessionByAccessHash, accessHash)
	var i SessionByAccessHashRow
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.UserID,
		&i.AccessExpiresAt,
		&i.RevokedAt,
		&i.EmailVerifiedAt,
	)
	return i, err
}

const sessionByRefreshHashForUpdate = `-- name: SessionByRefreshHashForUpdate :one
SELECT s.id, s.family_id, s.user_id, s.refresh_expires_at, s.replaced_by, s.revoked_at,
       u.email, u.email_verified_at
FROM sessions s JOIN users u ON u.id = s.user_id
WHERE s.refresh_hash = $1
FOR UPDATE OF s
`

type SessionByRefreshHashForUpdateRow struct {
	ID               pgtype.UUID
	FamilyID         pgtype.UUID
	UserID           pgtype.UUID
	RefreshExpiresAt pgtype.Timestamptz
	ReplacedBy       pgtype.UUID
	RevokedAt        pgtype.Timestamptz
	Email            string
	EmailVerifiedAt  pgtype.Timestamptz
}

func (q *Queries) SessionByRefreshHashForUpdate(ctx context.Context, refreshHash []byte) (SessionByRefreshHashForUpdateRow, error) {
	row := q.db.QueryRow(ctx, sessionByRefreshHashForUpdate, refreshHash)
	var i SessionByRefreshHashForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.UserID,
		&i.RefreshExpiresAt,
		&i.ReplacedBy,
		&i.RevokedAt,
		&i.Email,
		&i.EmailVerifiedAt,
	)
	return i, err
}

const setLoginNextAllowed = `-- name: SetLoginNextAllowed :exec
UPDATE login_throttle SET next_allowed_at = $1
WHERE scope = $2 AND key = $3
`

type SetLoginNextAllowedParams struct {
	NextAllowedAt pgtype.Timestamptz
	Scope         string
	Key           []byte
}

func (q *Queries) SetLoginNextAllowed(ctx context.Context, arg SetLoginNextAllowedParams) error {
	_, err := q.db.Exec(ctx, setLoginNextAllowed, arg.NextAllowedAt, arg.Scope, arg.Key)
	return err
}

const upsertUnverifiedUser = `-- name: UpsertUnverifiedUser :one
INSERT INTO users (id, email, password_hash, created_at, updated_at)
VALUES ($1, $2, $3, $4, $4)
ON CONFLICT (email) DO UPDATE
    SET password_hash = excluded.password_hash,
        updated_at = excluded.updated_at,
        version = users.version + 1
    WHERE users.email_verified_at IS NULL
RETURNING id, email, email_verified_at
`

type UpsertUnverifiedUserParams struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
	Now          pgtype.Timestamptz
}

type UpsertUnverifiedUserRow struct {
	ID              pgtype.UUID
	Email           string
	EmailVerifiedAt pgtype.Timestamptz
}

// Creates the User, or replaces the password of the unverified User with the
// same email. Returns no row when a verified User has the email.
func (q *Queries) UpsertUnverifiedUser(ctx context.Context, arg UpsertUnverifiedUserParams) (UpsertUnverifiedUserRow, error) {
	row := q.db.QueryRow(ctx, upsertUnverifiedUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.Now,
	)
	var i UpsertUnverifiedUserRow
	err := row.Scan(&i.ID, &i.Email, &i.EmailVerifiedAt)
	return i, err
}

const userByEmail = `-- name: UserByEmail :one
SELECT id, email, password_hash, email_verified_at FROM users WHERE email = $1
`

type UserByEmailRow struct {
	ID              pgtype.UUID
	Email           string
	PasswordHash    string
	EmailVerifiedAt pgtype.Timestamptz
}

func (q *Queries) UserByEmail(ctx context.Context, email string) (UserByEmailRow, error) {
	row := q.db.QueryRow(ctx, userByEmail, email)
	var i UserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
	)
	return i, err
}

const userByID = `-- name: UserByID :one
SELECT id, email, email_verified_at FROM users WHERE id = $1
`

type UserByIDRow struct {
	ID              pgtype.UUID
	Email           string
	EmailVerifiedAt pgtype.Timestamptz
}

func (q *Queries) UserByID(ctx context.Context, id pgtype.UUID) (UserByIDRow, error) {
	row := q.db.QueryRow(ctx, userByID, id)
	var i UserByIDRow
	err := row.Scan(&i.ID, &i.Email, &i.EmailVerifiedAt)
	return i, err
}
