// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeCode = `-- name: ConsumeCode :one
UPDATE one_time_codes SET consumed_at = $1
WHERE id = $2 AND consumed_at IS NULL
RETURNING user_id
`

type ConsumeCodeParams struct {
	Now pgtype.Timestamptz
	ID  pgtype.UUID
}

func (q *Queries) ConsumeCode(ctx context.Context, arg ConsumeCodeParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, consumeCode, arg.Now, arg.ID)
	var user_id pgtype.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const countCodeAttempt = `-- name: CountCodeAttempt :execrows
UPDATE one_time_codes SET attempts = attempts + 1
WHERE id = $1 AND consumed_at IS NULL AND attempts < $2::integer
`

type CountCodeAttemptParams struct {
	ID          pgtype.UUID
	MaxAttempts int32
}

func (q *Queries) CountCodeAttempt(ctx context.Context, arg CountCodeAttemptParams) (int64, error) {
	result, err := q.db.Exec(ctx, countCodeAttempt, arg.ID, arg.MaxAttempts)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUserCodes = `-- name: DeleteUserCodes :exec
DELETE FROM one_time_codes WHERE user_id = $1 AND purpose = $2
`

type DeleteUserCodesParams struct {
	UserID  pgtype.UUID
	Purpose string
}

func (q *Queries) DeleteUserCodes(ctx context.Context, arg DeleteUserCodesParams) error {
	_, err := q.db.Exec(ctx, deleteUserCodes, arg.UserID, arg.Purpose)
	return err
}

const insertCode = `-- name: InsertCode :exec
INSERT INTO one_time_codes (id, user_id, purpose, code_hash, expires_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertCodeParams struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Purpose   string
	CodeHash  []byte
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) InsertCode(ctx context.Context, arg InsertCodeParams) error {
	_, err := q.db.Exec(ctx, insertCode,
		arg.ID,
		arg.UserID,
		arg.Purpose,
		arg.CodeHash,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const insertSession = `-- name: InsertSession :exec
INSERT INTO sessions (id, user_id, access_hash, access_expires_at, refresh_hash, refresh_expires_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertSessionParams struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	AccessHash       []byte
	AccessExpiresAt  pgtype.Timestamptz
	RefreshHash      []byte
	RefreshExpiresAt pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.Exec(ctx, insertSession,
		arg.ID,
		arg.UserID,
		arg.AccessHash,
		arg.AccessExpiresAt,
		arg.RefreshHash,
		arg.RefreshExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const liveCode = `-- name: LiveCode :one
SELECT id, code_hash, expires_at, attempts FROM one_time_codes
WHERE user_id = $1 AND purpose = $2 AND consumed_at IS NULL
`

type LiveCodeParams struct {
	UserID  pgtype.UUID
	Purpose string
}

type LiveCodeRow struct {
	ID        pgtype.UUID
	CodeHash  []byte
	ExpiresAt pgtype.Timestamptz
	Attempts  int32
}

func (q *Queries) LiveCode(ctx context.Context, arg LiveCodeParams) (LiveCodeRow, error) {
	row := q.db.QueryRow(ctx, liveCode, arg.UserID, arg.Purpose)
	var i LiveCodeRow
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.Attempts,
	)
	return i, err
}

const markEmailVerified = `-- name: MarkEmailVerified :exec
UPDATE users SET email_verified_at = $1, updated_at = $1, version = version + 1
WHERE id = $2 AND email_verified_at IS NULL
`

type MarkEmailVerifiedParams struct {
	Now pgtype.Timestamptz
	ID  pgtype.UUID
}

func (q *Queries) MarkEmailVerified(ctx context.Context, arg MarkEmailVerifiedParams) error {
	_, err := q.db.Exec(ctx, markEmailVerified, arg.Now, arg.ID)
	return err
}

const revokeUserSessions = `-- name: RevokeUserSessions :exec
UPDATE sessions SET revoked_at = $1
WHERE user_id = $2 AND revoked_at IS NULL
`

type RevokeUserSessionsParams struct {
	Now    pgtype.Timestamptz
	UserID pgtype.UUID
}

func (q *Queries) RevokeUserSessions(ctx context.Context, arg RevokeUserSessionsParams) error {
	_, err := q.db.Exec(ctx, revokeUserSessions, arg.Now, arg.UserID)
	return err
}

const sessionByAccessHash = `-- name: SessionByAccessHash :one
SELECT s.id, s.user_id, s.access_expires_at, s.revoked_at, u.email_verified_at
FROM sessions s JOIN users u ON u.id = s.user_id
WHERE s.access_hash = $1
`

type SessionByAccessHashRow struct {
	ID              pgtype.UUID
	UserID          pgtype.UUID
	AccessExpiresAt pgtype.Timestamptz
	RevokedAt       pgtype.Timestamptz
	EmailVerifiedAt pgtype.Timestamptz
}

func (q *Queries) SessionByAccessHash(ctx context.Context, accessHash []byte) (SessionByAccessHashRow, error) {
	row := q.db.QueryRow(ctx, sessionByAccessHash, accessHash)
	var i SessionByAccessHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccessExpiresAt,
		&i.RevokedAt,
		&i.EmailVerifiedAt,
	)
	return i, err
}

const upsertUnverifiedUser = `-- name: UpsertUnverifiedUser :one
INSERT INTO users (id, email, password_hash, created_at, updated_at)
VALUES ($1, $2, $3, $4, $4)
ON CONFLICT (email) DO UPDATE
    SET password_hash = excluded.password_hash,
        updated_at = excluded.updated_at,
        version = users.version + 1
    WHERE users.email_verified_at IS NULL
RETURNING id, email, email_verified_at
`

type UpsertUnverifiedUserParams struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
	Now          pgtype.Timestamptz
}

type UpsertUnverifiedUserRow struct {
	ID              pgtype.UUID
	Email           string
	EmailVerifiedAt pgtype.Timestamptz
}

// Creates the User, or replaces the password of the unverified User with the
// same email. Returns no row when a verified User has the email.
func (q *Queries) UpsertUnverifiedUser(ctx context.Context, arg UpsertUnverifiedUserParams) (UpsertUnverifiedUserRow, error) {
	row := q.db.QueryRow(ctx, upsertUnverifiedUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.Now,
	)
	var i UpsertUnverifiedUserRow
	err := row.Scan(&i.ID, &i.Email, &i.EmailVerifiedAt)
	return i, err
}

const userByEmail = `-- name: UserByEmail :one
SELECT id, email, password_hash, email_verified_at FROM users WHERE email = $1
`

type UserByEmailRow struct {
	ID              pgtype.UUID
	Email           string
	PasswordHash    string
	EmailVerifiedAt pgtype.Timestamptz
}

func (q *Queries) UserByEmail(ctx context.Context, email string) (UserByEmailRow, error) {
	row := q.db.QueryRow(ctx, userByEmail, email)
	var i UserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
	)
	return i, err
}

const userByID = `-- name: UserByID :one
SELECT id, email, email_verified_at FROM users WHERE id = $1
`

type UserByIDRow struct {
	ID              pgtype.UUID
	Email           string
	EmailVerifiedAt pgtype.Timestamptz
}

func (q *Queries) UserByID(ctx context.Context, id pgtype.UUID) (UserByIDRow, error) {
	row := q.db.QueryRow(ctx, userByID, id)
	var i UserByIDRow
	err := row.Scan(&i.ID, &i.Email, &i.EmailVerifiedAt)
	return i, err
}
