// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: balances.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const ledgerExpenses = `-- name: LedgerExpenses :many
SELECT e.id, e.state, p.join_seq AS payer_join_seq, e.amount_minor
FROM expenses e JOIN members p ON p.id = e.payer_id
WHERE e.group_id = $1
`

type LedgerExpensesRow struct {
	ID           pgtype.UUID
	State        string
	PayerJoinSeq int32
	AmountMinor  int64
}

func (q *Queries) LedgerExpenses(ctx context.Context, groupID pgtype.UUID) ([]LedgerExpensesRow, error) {
	rows, err := q.db.Query(ctx, ledgerExpenses, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LedgerExpensesRow{}
	for rows.Next() {
		var i LedgerExpensesRow
		if err := rows.Scan(
			&i.ID,
			&i.State,
			&i.PayerJoinSeq,
			&i.AmountMinor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ledgerMembers = `-- name: LedgerMembers :many
SELECT id, join_seq FROM members WHERE group_id = $1 ORDER BY join_seq
`

type LedgerMembersRow struct {
	ID      pgtype.UUID
	JoinSeq int32
}

func (q *Queries) LedgerMembers(ctx context.Context, groupID pgtype.UUID) ([]LedgerMembersRow, error) {
	rows, err := q.db.Query(ctx, ledgerMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LedgerMembersRow{}
	for rows.Next() {
		var i LedgerMembersRow
		if err := rows.Scan(&i.ID, &i.JoinSeq); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ledgerShares = `-- name: LedgerShares :many
SELECT s.expense_id, m.join_seq, s.share_minor
FROM expense_shares s
JOIN expenses e ON e.id = s.expense_id
JOIN members m ON m.id = s.member_id
WHERE e.group_id = $1
`

type LedgerSharesRow struct {
	ExpenseID  pgtype.UUID
	JoinSeq    int32
	ShareMinor int64
}

func (q *Queries) LedgerShares(ctx context.Context, groupID pgtype.UUID) ([]LedgerSharesRow, error) {
	rows, err := q.db.Query(ctx, ledgerShares, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LedgerSharesRow{}
	for rows.Next() {
		var i LedgerSharesRow
		if err := rows.Scan(&i.ExpenseID, &i.JoinSeq, &i.ShareMinor); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
