// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: expenses.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteShares = `-- name: DeleteShares :exec
DELETE FROM expense_shares WHERE expense_id = $1
`

// Before a revision's Shares are written; the old ones are kept in its
// `expense_edited` event.
func (q *Queries) DeleteShares(ctx context.Context, expenseID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteShares, expenseID)
	return err
}

const expenseForUser = `-- name: ExpenseForUser :one
SELECT e.id, e.group_id, e.created_by, e.payer_id, e.category, e.note, e.spent_on, e.original_minor,
       e.original_currency, e.exchange_rate, e.amount_minor, e.split_method, e.state, e.revision, e.version, e.created_at,
       g.currency
FROM expenses e
JOIN groups g ON g.id = e.group_id
JOIN members m ON m.group_id = e.group_id
WHERE e.id = $1 AND m.user_id = $2 AND m.status = 'active'
`

type ExpenseForUserParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

type ExpenseForUserRow struct {
	ID               pgtype.UUID
	GroupID          pgtype.UUID
	CreatedBy        pgtype.UUID
	PayerID          pgtype.UUID
	Category         string
	Note             pgtype.Text
	SpentOn          pgtype.Date
	OriginalMinor    int64
	OriginalCurrency string
	ExchangeRate     pgtype.Numeric
	AmountMinor      int64
	SplitMethod      string
	State            string
	Revision         int32
	Version          int32
	CreatedAt        pgtype.Timestamptz
	Currency         string
}

// The Expense, if the User is an active Member of its Group.
func (q *Queries) ExpenseForUser(ctx context.Context, arg ExpenseForUserParams) (ExpenseForUserRow, error) {
	row := q.db.QueryRow(ctx, expenseForUser, arg.ID, arg.UserID)
	var i ExpenseForUserRow
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.CreatedBy,
		&i.PayerID,
		&i.Category,
		&i.Note,
		&i.SpentOn,
		&i.OriginalMinor,
		&i.OriginalCurrency,
		&i.ExchangeRate,
		&i.AmountMinor,
		&i.SplitMethod,
		&i.State,
		&i.Revision,
		&i.Version,
		&i.CreatedAt,
		&i.Currency,
	)
	return i, err
}

const expenseShares = `-- name: ExpenseShares :many
SELECT s.member_id, s.share_minor, s.input
FROM expense_shares s JOIN members m ON m.id = s.member_id
WHERE s.expense_id = $1
ORDER BY m.join_seq
`

type ExpenseSharesRow struct {
	MemberID   pgtype.UUID
	ShareMinor int64
	Input      pgtype.Numeric
}

func (q *Queries) ExpenseShares(ctx context.Context, expenseID pgtype.UUID) ([]ExpenseSharesRow, error) {
	rows, err := q.db.Query(ctx, expenseShares, expenseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpenseSharesRow{}
	for rows.Next() {
		var i ExpenseSharesRow
		if err := rows.Scan(&i.MemberID, &i.ShareMinor, &i.Input); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertActivityEvent = `-- name: InsertActivityEvent :exec
INSERT INTO activity_events (group_id, actor_member_id, on_behalf_of_member_id, type, subject_type, subject_id,
                             payload, occurred_at)
VALUES ($1, $2, $3, $4, $5, $6,
        $7, $8)
`

type InsertActivityEventParams struct {
	GroupID            pgtype.UUID
	ActorMemberID      pgtype.UUID
	OnBehalfOfMemberID pgtype.UUID
	Type               string
	SubjectType        string
	SubjectID          pgtype.UUID
	Payload            []byte
	OccurredAt         pgtype.Timestamptz
}

func (q *Queries) InsertActivityEvent(ctx context.Context, arg InsertActivityEventParams) error {
	_, err := q.db.Exec(ctx, insertActivityEvent,
		arg.GroupID,
		arg.ActorMemberID,
		arg.OnBehalfOfMemberID,
		arg.Type,
		arg.SubjectType,
		arg.SubjectID,
		arg.Payload,
		arg.OccurredAt,
	)
	return err
}

const insertExpense = `-- name: InsertExpense :exec
INSERT INTO expenses (id, group_id, created_by, payer_id, category, note, spent_on, original_minor,
                      original_currency, exchange_rate, amount_minor, split_method, state, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8,
        $9, $10, $11, $12, $13, $14, $14)
`

type InsertExpenseParams struct {
	ID               pgtype.UUID
	GroupID          pgtype.UUID
	CreatedBy        pgtype.UUID
	PayerID          pgtype.UUID
	Category         string
	Note             pgtype.Text
	SpentOn          pgtype.Date
	OriginalMinor    int64
	OriginalCurrency string
	ExchangeRate     pgtype.Numeric
	AmountMinor      int64
	SplitMethod      string
	State            string
	Now              pgtype.Timestamptz
}

func (q *Queries) InsertExpense(ctx context.Context, arg InsertExpenseParams) error {
	_, err := q.db.Exec(ctx, insertExpense,
		arg.ID,
		arg.GroupID,
		arg.CreatedBy,
		arg.PayerID,
		arg.Category,
		arg.Note,
		arg.SpentOn,
		arg.OriginalMinor,
		arg.OriginalCurrency,
		arg.ExchangeRate,
		arg.AmountMinor,
		arg.SplitMethod,
		arg.State,
		arg.Now,
	)
	return err
}

const insertShare = `-- name: InsertShare :exec
INSERT INTO expense_shares (expense_id, member_id, input, share_minor)
VALUES ($1, $2, $3, $4)
`

type InsertShareParams struct {
	ExpenseID  pgtype.UUID
	MemberID   pgtype.UUID
	Input      pgtype.Numeric
	ShareMinor int64
}

func (q *Queries) InsertShare(ctx context.Context, arg InsertShareParams) error {
	_, err := q.db.Exec(ctx, insertShare,
		arg.ExpenseID,
		arg.MemberID,
		arg.Input,
		arg.ShareMinor,
	)
	return err
}

const listExpenses = `-- name: ListExpenses :many
SELECT e.id, e.payer_id, e.category, e.note, e.spent_on, e.amount_minor, e.state, g.currency
FROM expenses e JOIN groups g ON g.id = e.group_id
WHERE e.group_id = $1
  AND (NOT $2::boolean OR (e.spent_on, e.id) < ($3::date, $4::uuid))
ORDER BY e.spent_on DESC, e.id DESC
LIMIT $5
`

type ListExpensesParams struct {
	GroupID      pgtype.UUID
	HasCursor    bool
	AfterSpentOn pgtype.Date
	AfterID      pgtype.UUID
	MaxRows      int32
}

type ListExpensesRow struct {
	ID          pgtype.UUID
	PayerID     pgtype.UUID
	Category    string
	Note        pgtype.Text
	SpentOn     pgtype.Date
	AmountMinor int64
	State       string
	Currency    string
}

// One page, newest first; after_* is the last row of the previous page.
func (q *Queries) ListExpenses(ctx context.Context, arg ListExpensesParams) ([]ListExpensesRow, error) {
	rows, err := q.db.Query(ctx, listExpenses,
		arg.GroupID,
		arg.HasCursor,
		arg.AfterSpentOn,
		arg.AfterID,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpensesRow{}
	for rows.Next() {
		var i ListExpensesRow
		if err := rows.Scan(
			&i.ID,
			&i.PayerID,
			&i.Category,
			&i.Note,
			&i.SpentOn,
			&i.AmountMinor,
			&i.State,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockGroupShared = `-- name: LockGroupShared :one
SELECT state, currency FROM groups WHERE id = $1 FOR SHARE
`

type LockGroupSharedRow struct {
	State    string
	Currency string
}

// Holds the Group's state steady while an Expense is written.
func (q *Queries) LockGroupShared(ctx context.Context, id pgtype.UUID) (LockGroupSharedRow, error) {
	row := q.db.QueryRow(ctx, lockGroupShared, id)
	var i LockGroupSharedRow
	err := row.Scan(&i.State, &i.Currency)
	return i, err
}

const setExpenseState = `-- name: SetExpenseState :one
UPDATE expenses SET state = $1, updated_at = $2, version = version + 1
WHERE id = $3 AND version = $4 AND state = $5
RETURNING version
`

type SetExpenseStateParams struct {
	State     string
	Now       pgtype.Timestamptz
	ID        pgtype.UUID
	Version   int32
	FromState string
}

func (q *Queries) SetExpenseState(ctx context.Context, arg SetExpenseStateParams) (int32, error) {
	row := q.db.QueryRow(ctx, setExpenseState,
		arg.State,
		arg.Now,
		arg.ID,
		arg.Version,
		arg.FromState,
	)
	var version int32
	err := row.Scan(&version)
	return version, err
}

const updateExpense = `-- name: UpdateExpense :one
UPDATE expenses
SET payer_id = $1, category = $2, note = $3, spent_on = $4, original_minor = $5,
    original_currency = $6, exchange_rate = $7, amount_minor = $8,
    split_method = $9, state = $10, revision = revision + 1, updated_at = $11, version = version + 1
WHERE id = $12 AND version = $13 AND state = $14
RETURNING revision, version
`

type UpdateExpenseParams struct {
	PayerID          pgtype.UUID
	Category         string
	Note             pgtype.Text
	SpentOn          pgtype.Date
	OriginalMinor    int64
	OriginalCurrency string
	ExchangeRate     pgtype.Numeric
	AmountMinor      int64
	SplitMethod      string
	State            string
	Now              pgtype.Timestamptz
	ID               pgtype.UUID
	Version          int32
	FromState        string
}

type UpdateExpenseRow struct {
	Revision int32
	Version  int32
}

// A new revision of the Expense, if it is still at version and in from_state.
func (q *Queries) UpdateExpense(ctx context.Context, arg UpdateExpenseParams) (UpdateExpenseRow, error) {
	row := q.db.QueryRow(ctx, updateExpense,
		arg.PayerID,
		arg.Category,
		arg.Note,
		arg.SpentOn,
		arg.OriginalMinor,
		arg.OriginalCurrency,
		arg.ExchangeRate,
		arg.AmountMinor,
		arg.SplitMethod,
		arg.State,
		arg.Now,
		arg.ID,
		arg.Version,
		arg.FromState,
	)
	var i UpdateExpenseRow
	err := row.Scan(&i.Revision, &i.Version)
	return i, err
}
