// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: groups.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveMemberships = `-- name: CountActiveMemberships :one
SELECT count(*) FROM members WHERE user_id = $1 AND status = 'active'
`

func (q *Queries) CountActiveMemberships(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveMemberships, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMembers = `-- name: CountMembers :one
SELECT count(*) FROM members WHERE group_id = $1
`

func (q *Queries) CountMembers(ctx context.Context, groupID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMembers, groupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const displayNameExists = `-- name: DisplayNameExists :one
SELECT EXISTS (
    SELECT 1 FROM members WHERE group_id = $1 AND lower(display_name) = lower($2)
)
`

type DisplayNameExistsParams struct {
	GroupID     pgtype.UUID
	DisplayName string
}

func (q *Queries) DisplayNameExists(ctx context.Context, arg DisplayNameExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, displayNameExists, arg.GroupID, arg.DisplayName)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const groupForMember = `-- name: GroupForMember :one
SELECT g.id, g.name, g.currency, g.state, g.version, m.id AS my_member_id, m.role AS my_role
FROM groups g JOIN members m ON m.group_id = g.id
WHERE g.id = $1 AND m.user_id = $2 AND m.status = 'active'
`

type GroupForMemberParams struct {
	GroupID pgtype.UUID
	UserID  pgtype.UUID
}

type GroupForMemberRow struct {
	ID         pgtype.UUID
	Name       string
	Currency   string
	State      string
	Version    int32
	MyMemberID pgtype.UUID
	MyRole     string
}

// The Group, if the User is an active Member of it, with that Member.
func (q *Queries) GroupForMember(ctx context.Context, arg GroupForMemberParams) (GroupForMemberRow, error) {
	row := q.db.QueryRow(ctx, groupForMember, arg.GroupID, arg.UserID)
	var i GroupForMemberRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Currency,
		&i.State,
		&i.Version,
		&i.MyMemberID,
		&i.MyRole,
	)
	return i, err
}

const groupMembers = `-- name: GroupMembers :many
SELECT id, user_id, display_name, role, status, join_seq, version FROM members
WHERE group_id = $1
ORDER BY join_seq
`

type GroupMembersRow struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	DisplayName string
	Role        string
	Status      string
	JoinSeq     int32
	Version     int32
}

func (q *Queries) GroupMembers(ctx context.Context, groupID pgtype.UUID) ([]GroupMembersRow, error) {
	rows, err := q.db.Query(ctx, groupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GroupMembersRow{}
	for rows.Next() {
		var i GroupMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DisplayName,
			&i.Role,
			&i.Status,
			&i.JoinSeq,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertGroup = `-- name: InsertGroup :exec
INSERT INTO groups (id, name, currency, created_at, updated_at)
VALUES ($1, $2, $3, $4, $4)
`

type InsertGroupParams struct {
	ID       pgtype.UUID
	Name     string
	Currency string
	Now      pgtype.Timestamptz
}

func (q *Queries) InsertGroup(ctx context.Context, arg InsertGroupParams) error {
	_, err := q.db.Exec(ctx, insertGroup,
		arg.ID,
		arg.Name,
		arg.Currency,
		arg.Now,
	)
	return err
}

const insertMember = `-- name: InsertMember :one
INSERT INTO members (id, group_id, user_id, display_name, email, role, join_seq, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6,
        (SELECT coalesce(max(join_seq), 0) + 1 FROM members WHERE group_id = $2), $7, $7)
RETURNING id, user_id, display_name, role, status, join_seq, version
`

type InsertMemberParams struct {
	ID          pgtype.UUID
	GroupID     pgtype.UUID
	UserID      pgtype.UUID
	DisplayName string
	Email       pgtype.Text
	Role        string
	Now         pgtype.Timestamptz
}

type InsertMemberRow struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	DisplayName string
	Role        string
	Status      string
	JoinSeq     int32
	Version     int32
}

// Call with the Group row locked (LockGroup), so join_seq is the next one.
func (q *Queries) InsertMember(ctx context.Context, arg InsertMemberParams) (InsertMemberRow, error) {
	row := q.db.QueryRow(ctx, insertMember,
		arg.ID,
		arg.GroupID,
		arg.UserID,
		arg.DisplayName,
		arg.Email,
		arg.Role,
		arg.Now,
	)
	var i InsertMemberRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Role,
		&i.Status,
		&i.JoinSeq,
		&i.Version,
	)
	return i, err
}

const listGroupsForUser = `-- name: ListGroupsForUser :many
SELECT g.id, g.name, g.currency, g.state
FROM groups g JOIN members m ON m.group_id = g.id
WHERE m.user_id = $1 AND m.status = 'active' AND g.id > $2
ORDER BY g.id
LIMIT $3
`

type ListGroupsForUserParams struct {
	UserID  pgtype.UUID
	After   pgtype.UUID
	MaxRows int32
}

type ListGroupsForUserRow struct {
	ID       pgtype.UUID
	Name     string
	Currency string
	State    string
}

func (q *Queries) ListGroupsForUser(ctx context.Context, arg ListGroupsForUserParams) ([]ListGroupsForUserRow, error) {
	rows, err := q.db.Query(ctx, listGroupsForUser, arg.UserID, arg.After, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGroupsForUserRow{}
	for rows.Next() {
		var i ListGroupsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Currency,
			&i.State,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockGroup = `-- name: LockGroup :one
SELECT state FROM groups WHERE id = $1 FOR UPDATE
`

// Serializes changes to a Group's Members (join_seq, the 50 limit).
func (q *Queries) LockGroup(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, lockGroup, id)
	var state string
	err := row.Scan(&state)
	return state, err
}

const lockUser = `-- name: LockUser :exec
SELECT id FROM users WHERE id = $1 FOR UPDATE
`

// Serializes a User's Group creations, so the 200-Group limit holds.
func (q *Queries) LockUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, lockUser, id)
	return err
}

const memberEmailOrUserExists = `-- name: MemberEmailOrUserExists :one
SELECT EXISTS (
    SELECT 1 FROM members m LEFT JOIN users u ON u.id = m.user_id
    WHERE m.group_id = $1 AND (m.email = $2 OR u.email = $2)
)
`

type MemberEmailOrUserExistsParams struct {
	GroupID pgtype.UUID
	Email   pgtype.Text
}

// Whether the email is already in the Group, as a Placeholder's email or as
// the email of a Member's User.
func (q *Queries) MemberEmailOrUserExists(ctx context.Context, arg MemberEmailOrUserExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, memberEmailOrUserExists, arg.GroupID, arg.Email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const memberInGroup = `-- name: MemberInGroup :one
SELECT id, user_id, display_name, role, status, join_seq, version FROM members
WHERE group_id = $1 AND id = $2
`

type MemberInGroupParams struct {
	GroupID pgtype.UUID
	ID      pgtype.UUID
}

type MemberInGroupRow struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	DisplayName string
	Role        string
	Status      string
	JoinSeq     int32
	Version     int32
}

func (q *Queries) MemberInGroup(ctx context.Context, arg MemberInGroupParams) (MemberInGroupRow, error) {
	row := q.db.QueryRow(ctx, memberInGroup, arg.GroupID, arg.ID)
	var i MemberInGroupRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Role,
		&i.Status,
		&i.JoinSeq,
		&i.Version,
	)
	return i, err
}

const renameGroup = `-- name: RenameGroup :execrows
UPDATE groups SET name = $1, updated_at = $2, version = version + 1
WHERE id = $3 AND version = $4
`

type RenameGroupParams struct {
	Name    string
	Now     pgtype.Timestamptz
	ID      pgtype.UUID
	Version int32
}

func (q *Queries) RenameGroup(ctx context.Context, arg RenameGroupParams) (int64, error) {
	result, err := q.db.Exec(ctx, renameGroup,
		arg.Name,
		arg.Now,
		arg.ID,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setMemberRole = `-- name: SetMemberRole :one
UPDATE members SET role = $1, updated_at = $2, version = version + 1
WHERE group_id = $3 AND id = $4 AND version = $5
RETURNING id, user_id, display_name, role, status, join_seq, version
`

type SetMemberRoleParams struct {
	Role    string
	Now     pgtype.Timestamptz
	GroupID pgtype.UUID
	ID      pgtype.UUID
	Version int32
}

type SetMemberRoleRow struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	DisplayName string
	Role        string
	Status      string
	JoinSeq     int32
	Version     int32
}

func (q *Queries) SetMemberRole(ctx context.Context, arg SetMemberRoleParams) (SetMemberRoleRow, error) {
	row := q.db.QueryRow(ctx, setMemberRole,
		arg.Role,
		arg.Now,
		arg.GroupID,
		arg.ID,
		arg.Version,
	)
	var i SetMemberRoleRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Role,
		&i.Status,
		&i.JoinSeq,
		&i.Version,
	)
	return i, err
}

const verifiedUserIDByEmail = `-- name: VerifiedUserIDByEmail :one
SELECT id FROM users WHERE email = $1 AND email_verified_at IS NOT NULL
`

func (q *Queries) VerifiedUserIDByEmail(ctx context.Context, email string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, verifiedUserIDByEmail, email)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
