// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: groups.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveMemberships = `-- name: CountActiveMemberships :one
SELECT count(*) FROM members WHERE user_id = $1 AND status = 'active'
`

func (q *Queries) CountActiveMemberships(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveMemberships, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const groupForMember = `-- name: GroupForMember :one
SELECT g.id, g.name, g.currency, g.state, g.version, m.id AS my_member_id, m.role AS my_role
FROM groups g JOIN members m ON m.group_id = g.id
WHERE g.id = $1 AND m.user_id = $2 AND m.status = 'active'
`

type GroupForMemberParams struct {
	GroupID pgtype.UUID
	UserID  pgtype.UUID
}

type GroupForMemberRow struct {
	ID         pgtype.UUID
	Name       string
	Currency   string
	State      string
	Version    int32
	MyMemberID pgtype.UUID
	MyRole     string
}

// The Group, if the User is an active Member of it, with that Member.
func (q *Queries) GroupForMember(ctx context.Context, arg GroupForMemberParams) (GroupForMemberRow, error) {
	row := q.db.QueryRow(ctx, groupForMember, arg.GroupID, arg.UserID)
	var i GroupForMemberRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Currency,
		&i.State,
		&i.Version,
		&i.MyMemberID,
		&i.MyRole,
	)
	return i, err
}

const groupMembers = `-- name: GroupMembers :many
SELECT id, user_id, display_name, role, status, join_seq FROM members
WHERE group_id = $1
ORDER BY join_seq
`

type GroupMembersRow struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	DisplayName string
	Role        string
	Status      string
	JoinSeq     int32
}

func (q *Queries) GroupMembers(ctx context.Context, groupID pgtype.UUID) ([]GroupMembersRow, error) {
	rows, err := q.db.Query(ctx, groupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GroupMembersRow{}
	for rows.Next() {
		var i GroupMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DisplayName,
			&i.Role,
			&i.Status,
			&i.JoinSeq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertGroup = `-- name: InsertGroup :exec
INSERT INTO groups (id, name, currency, created_at, updated_at)
VALUES ($1, $2, $3, $4, $4)
`

type InsertGroupParams struct {
	ID       pgtype.UUID
	Name     string
	Currency string
	Now      pgtype.Timestamptz
}

func (q *Queries) InsertGroup(ctx context.Context, arg InsertGroupParams) error {
	_, err := q.db.Exec(ctx, insertGroup,
		arg.ID,
		arg.Name,
		arg.Currency,
		arg.Now,
	)
	return err
}

const insertMember = `-- name: InsertMember :exec
INSERT INTO members (id, group_id, user_id, display_name, email, role, join_seq, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6,
        (SELECT coalesce(max(join_seq), 0) + 1 FROM members WHERE group_id = $2), $7, $7)
`

type InsertMemberParams struct {
	ID          pgtype.UUID
	GroupID     pgtype.UUID
	UserID      pgtype.UUID
	DisplayName string
	Email       pgtype.Text
	Role        string
	Now         pgtype.Timestamptz
}

func (q *Queries) InsertMember(ctx context.Context, arg InsertMemberParams) error {
	_, err := q.db.Exec(ctx, insertMember,
		arg.ID,
		arg.GroupID,
		arg.UserID,
		arg.DisplayName,
		arg.Email,
		arg.Role,
		arg.Now,
	)
	return err
}

const listGroupsForUser = `-- name: ListGroupsForUser :many
SELECT g.id, g.name, g.currency, g.state
FROM groups g JOIN members m ON m.group_id = g.id
WHERE m.user_id = $1 AND m.status = 'active' AND g.id > $2
ORDER BY g.id
LIMIT $3
`

type ListGroupsForUserParams struct {
	UserID  pgtype.UUID
	After   pgtype.UUID
	MaxRows int32
}

type ListGroupsForUserRow struct {
	ID       pgtype.UUID
	Name     string
	Currency string
	State    string
}

func (q *Queries) ListGroupsForUser(ctx context.Context, arg ListGroupsForUserParams) ([]ListGroupsForUserRow, error) {
	rows, err := q.db.Query(ctx, listGroupsForUser, arg.UserID, arg.After, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGroupsForUserRow{}
	for rows.Next() {
		var i ListGroupsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Currency,
			&i.State,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockUser = `-- name: LockUser :exec
SELECT id FROM users WHERE id = $1 FOR UPDATE
`

// Serializes a User's Group creations, so the 200-Group limit holds.
func (q *Queries) LockUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, lockUser, id)
	return err
}

const renameGroup = `-- name: RenameGroup :execrows
UPDATE groups SET name = $1, updated_at = $2, version = version + 1
WHERE id = $3 AND version = $4
`

type RenameGroupParams struct {
	Name    string
	Now     pgtype.Timestamptz
	ID      pgtype.UUID
	Version int32
}

func (q *Queries) RenameGroup(ctx context.Context, arg RenameGroupParams) (int64, error) {
	result, err := q.db.Exec(ctx, renameGroup,
		arg.Name,
		arg.Now,
		arg.ID,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
