// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimIdempotencyKey = `-- name: ClaimIdempotencyKey :one
INSERT INTO idempotency_keys (user_id, key, request_hash, status, created_at)
VALUES ($1, $2, $3, 'in_progress', $4)
ON CONFLICT (user_id, key) DO UPDATE
    SET request_hash = excluded.request_hash,
        status = 'in_progress',
        response_status = NULL,
        response_content_type = NULL,
        response_body = NULL,
        created_at = excluded.created_at
    WHERE idempotency_keys.created_at <= $5
RETURNING created_at
`

type ClaimIdempotencyKeyParams struct {
	UserID      pgtype.UUID
	Key         pgtype.UUID
	RequestHash []byte
	Now         pgtype.Timestamptz
	StaleBefore pgtype.Timestamptz
}

// Stores an in-progress key. A key created at or before @stale_before is past its
// 24 h and is replaced. Returns no row when a live key exists.
func (q *Queries) ClaimIdempotencyKey(ctx context.Context, arg ClaimIdempotencyKeyParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, claimIdempotencyKey,
		arg.UserID,
		arg.Key,
		arg.RequestHash,
		arg.Now,
		arg.StaleBefore,
	)
	var created_at pgtype.Timestamptz
	err := row.Scan(&created_at)
	return created_at, err
}

const completeIdempotencyKey = `-- name: CompleteIdempotencyKey :exec
UPDATE idempotency_keys
SET status = 'completed', response_status = $1,
    response_content_type = $2, response_body = $3
WHERE user_id = $4 AND key = $5 AND status = 'in_progress'
`

type CompleteIdempotencyKeyParams struct {
	ResponseStatus      pgtype.Int4
	ResponseContentType pgtype.Text
	ResponseBody        []byte
	UserID              pgtype.UUID
	Key                 pgtype.UUID
}

func (q *Queries) CompleteIdempotencyKey(ctx context.Context, arg CompleteIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, completeIdempotencyKey,
		arg.ResponseStatus,
		arg.ResponseContentType,
		arg.ResponseBody,
		arg.UserID,
		arg.Key,
	)
	return err
}

const idempotencyKey = `-- name: IdempotencyKey :one
SELECT request_hash, status, response_status, response_content_type, response_body
FROM idempotency_keys WHERE user_id = $1 AND key = $2
`

type IdempotencyKeyParams struct {
	UserID pgtype.UUID
	Key    pgtype.UUID
}

type IdempotencyKeyRow struct {
	RequestHash         []byte
	Status              string
	ResponseStatus      pgtype.Int4
	ResponseContentType pgtype.Text
	ResponseBody        []byte
}

func (q *Queries) IdempotencyKey(ctx context.Context, arg IdempotencyKeyParams) (IdempotencyKeyRow, error) {
	row := q.db.QueryRow(ctx, idempotencyKey, arg.UserID, arg.Key)
	var i IdempotencyKeyRow
	err := row.Scan(
		&i.RequestHash,
		&i.Status,
		&i.ResponseStatus,
		&i.ResponseContentType,
		&i.ResponseBody,
	)
	return i, err
}

const releaseIdempotencyKey = `-- name: ReleaseIdempotencyKey :exec
DELETE FROM idempotency_keys WHERE user_id = $1 AND key = $2 AND status = 'in_progress'
`

type ReleaseIdempotencyKeyParams struct {
	UserID pgtype.UUID
	Key    pgtype.UUID
}

func (q *Queries) ReleaseIdempotencyKey(ctx context.Context, arg ReleaseIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, releaseIdempotencyKey, arg.UserID, arg.Key)
	return err
}
