// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type IdempotencyKey struct {
	UserID              pgtype.UUID
	Key                 pgtype.UUID
	RequestHash         []byte
	Status              string
	ResponseStatus      pgtype.Int4
	ResponseContentType pgtype.Text
	ResponseBody        []byte
	CreatedAt           pgtype.Timestamptz
}

type LoginThrottle struct {
	Scope         string
	Key           []byte
	Failures      int32
	LastFailureAt pgtype.Timestamptz
	NextAllowedAt pgtype.Timestamptz
}

type OneTimeCode struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	Purpose    string
	CodeHash   []byte
	ExpiresAt  pgtype.Timestamptz
	Attempts   int32
	ConsumedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type Session struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	AccessHash       []byte
	AccessExpiresAt  pgtype.Timestamptz
	RefreshHash      []byte
	RefreshExpiresAt pgtype.Timestamptz
	ReplacedBy       pgtype.UUID
	RevokedAt        pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	FamilyID         pgtype.UUID
}

type User struct {
	ID              pgtype.UUID
	Email           string
	PasswordHash    string
	EmailVerifiedAt pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	Version         int32
}
