// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ActivityEvent struct {
	ID                 int64
	GroupID            pgtype.UUID
	ActorMemberID      pgtype.UUID
	OnBehalfOfMemberID pgtype.UUID
	Type               string
	SubjectType        string
	SubjectID          pgtype.UUID
	Payload            []byte
	OccurredAt         pgtype.Timestamptz
}

type Expense struct {
	ID               pgtype.UUID
	GroupID          pgtype.UUID
	CreatedBy        pgtype.UUID
	PayerID          pgtype.UUID
	Category         string
	Note             pgtype.Text
	SpentOn          pgtype.Date
	OriginalMinor    int64
	OriginalCurrency string
	ExchangeRate     pgtype.Numeric
	AmountMinor      int64
	SplitMethod      string
	State            string
	Revision         int32
	PendingSince     pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	Version          int32
}

type ExpenseShare struct {
	ExpenseID  pgtype.UUID
	MemberID   pgtype.UUID
	Input      pgtype.Numeric
	ShareMinor int64
}

type Group struct {
	ID            pgtype.UUID
	ParentGroupID pgtype.UUID
	Name          string
	Currency      string
	State         string
	ClosingSince  pgtype.Timestamptz
	ClosedAt      pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	Version       int32
}

type IdempotencyKey struct {
	UserID              pgtype.UUID
	Key                 pgtype.UUID
	RequestHash         []byte
	Status              string
	ResponseStatus      pgtype.Int4
	ResponseContentType pgtype.Text
	ResponseBody        []byte
	CreatedAt           pgtype.Timestamptz
}

type LoginThrottle struct {
	Scope         string
	Key           []byte
	Failures      int32
	LastFailureAt pgtype.Timestamptz
	NextAllowedAt pgtype.Timestamptz
}

type Member struct {
	ID             pgtype.UUID
	GroupID        pgtype.UUID
	UserID         pgtype.UUID
	DisplayName    string
	Email          pgtype.Text
	Role           string
	Status         string
	JoinSeq        int32
	ParentMemberID pgtype.UUID
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	Version        int32
}

type OneTimeCode struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	Purpose    string
	CodeHash   []byte
	ExpiresAt  pgtype.Timestamptz
	Attempts   int32
	ConsumedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type Session struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	AccessHash       []byte
	AccessExpiresAt  pgtype.Timestamptz
	RefreshHash      []byte
	RefreshExpiresAt pgtype.Timestamptz
	ReplacedBy       pgtype.UUID
	RevokedAt        pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	FamilyID         pgtype.UUID
}

type User struct {
	ID              pgtype.UUID
	Email           string
	PasswordHash    string
	EmailVerifiedAt pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	Version         int32
}
