// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settlements.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertSettlement = `-- name: InsertSettlement :exec
INSERT INTO settlements (id, group_id, from_member_id, to_member_id, amount_minor, settled_on, note, created_by,
                         state, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8,
        $9, $10, $10)
`

type InsertSettlementParams struct {
	ID           pgtype.UUID
	GroupID      pgtype.UUID
	FromMemberID pgtype.UUID
	ToMemberID   pgtype.UUID
	AmountMinor  int64
	SettledOn    pgtype.Date
	Note         pgtype.Text
	CreatedBy    pgtype.UUID
	State        string
	Now          pgtype.Timestamptz
}

func (q *Queries) InsertSettlement(ctx context.Context, arg InsertSettlementParams) error {
	_, err := q.db.Exec(ctx, insertSettlement,
		arg.ID,
		arg.GroupID,
		arg.FromMemberID,
		arg.ToMemberID,
		arg.AmountMinor,
		arg.SettledOn,
		arg.Note,
		arg.CreatedBy,
		arg.State,
		arg.Now,
	)
	return err
}

const ledgerSettlements = `-- name: LedgerSettlements :many
SELECT s.state, f.join_seq AS from_join_seq, t.join_seq AS to_join_seq, s.amount_minor
FROM settlements s
JOIN members f ON f.id = s.from_member_id
JOIN members t ON t.id = s.to_member_id
WHERE s.group_id = $1
`

type LedgerSettlementsRow struct {
	State       string
	FromJoinSeq int32
	ToJoinSeq   int32
	AmountMinor int64
}

func (q *Queries) LedgerSettlements(ctx context.Context, groupID pgtype.UUID) ([]LedgerSettlementsRow, error) {
	rows, err := q.db.Query(ctx, ledgerSettlements, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LedgerSettlementsRow{}
	for rows.Next() {
		var i LedgerSettlementsRow
		if err := rows.Scan(
			&i.State,
			&i.FromJoinSeq,
			&i.ToJoinSeq,
			&i.AmountMinor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSettlements = `-- name: ListSettlements :many
SELECT s.id, s.group_id, s.from_member_id, s.to_member_id, s.amount_minor, s.settled_on, s.note, s.created_by,
       s.state, s.version, s.created_at, g.currency
FROM settlements s JOIN groups g ON g.id = s.group_id
WHERE s.group_id = $1
  AND (NOT $2::boolean OR (s.settled_on, s.id) < ($3::date, $4::uuid))
ORDER BY s.settled_on DESC, s.id DESC
LIMIT $5
`

type ListSettlementsParams struct {
	GroupID        pgtype.UUID
	HasCursor      bool
	AfterSettledOn pgtype.Date
	AfterID        pgtype.UUID
	MaxRows        int32
}

type ListSettlementsRow struct {
	ID           pgtype.UUID
	GroupID      pgtype.UUID
	FromMemberID pgtype.UUID
	ToMemberID   pgtype.UUID
	AmountMinor  int64
	SettledOn    pgtype.Date
	Note         pgtype.Text
	CreatedBy    pgtype.UUID
	State        string
	Version      int32
	CreatedAt    pgtype.Timestamptz
	Currency     string
}

func (q *Queries) ListSettlements(ctx context.Context, arg ListSettlementsParams) ([]ListSettlementsRow, error) {
	rows, err := q.db.Query(ctx, listSettlements,
		arg.GroupID,
		arg.HasCursor,
		arg.AfterSettledOn,
		arg.AfterID,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSettlementsRow{}
	for rows.Next() {
		var i ListSettlementsRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.FromMemberID,
			&i.ToMemberID,
			&i.AmountMinor,
			&i.SettledOn,
			&i.Note,
			&i.CreatedBy,
			&i.State,
			&i.Version,
			&i.CreatedAt,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSettlementState = `-- name: SetSettlementState :one
UPDATE settlements SET state = $1, updated_at = $2, version = version + 1
WHERE id = $3 AND version = $4 AND state = $5
RETURNING version
`

type SetSettlementStateParams struct {
	State     string
	Now       pgtype.Timestamptz
	ID        pgtype.UUID
	Version   int32
	FromState string
}

func (q *Queries) SetSettlementState(ctx context.Context, arg SetSettlementStateParams) (int32, error) {
	row := q.db.QueryRow(ctx, setSettlementState,
		arg.State,
		arg.Now,
		arg.ID,
		arg.Version,
		arg.FromState,
	)
	var version int32
	err := row.Scan(&version)
	return version, err
}

const settlementForUser = `-- name: SettlementForUser :one
SELECT s.id, s.group_id, s.from_member_id, s.to_member_id, s.amount_minor, s.settled_on, s.note, s.created_by,
       s.state, s.version, s.created_at, g.currency, m.id AS my_member_id
FROM settlements s
JOIN groups g ON g.id = s.group_id
JOIN members m ON m.group_id = s.group_id
WHERE s.id = $1 AND m.user_id = $2 AND m.status = 'active'
`

type SettlementForUserParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

type SettlementForUserRow struct {
	ID           pgtype.UUID
	GroupID      pgtype.UUID
	FromMemberID pgtype.UUID
	ToMemberID   pgtype.UUID
	AmountMinor  int64
	SettledOn    pgtype.Date
	Note         pgtype.Text
	CreatedBy    pgtype.UUID
	State        string
	Version      int32
	CreatedAt    pgtype.Timestamptz
	Currency     string
	MyMemberID   pgtype.UUID
}

// The Settlement, if the User is an active Member of its Group.
func (q *Queries) SettlementForUser(ctx context.Context, arg SettlementForUserParams) (SettlementForUserRow, error) {
	row := q.db.QueryRow(ctx, settlementForUser, arg.ID, arg.UserID)
	var i SettlementForUserRow
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.FromMemberID,
		&i.ToMemberID,
		&i.AmountMinor,
		&i.SettledOn,
		&i.Note,
		&i.CreatedBy,
		&i.State,
		&i.Version,
		&i.CreatedAt,
		&i.Currency,
		&i.MyMemberID,
	)
	return i, err
}
